### ISSUE TITLE
Coroutine not working

### ISSUE THREAD

**Issue by Thedorner96** [ScrapComputers/ScrapComputers#4]
Im not very good with lua, however whenever i use a while loop to check if something is available, the entire game locks up.
Only way i can fix this is by editing the savefile and change the "while" text to some garble in order to be able to load into the game again.

Would be nice if there is a way to do "multithreading"

Other than that, Amazing mod!

**Comment by VeraDev0** [comment]
Scrap Mechanic doesn’t allow any kind of true multithreading. However, we can implement cooperative multithreading (hence the name, **co**routines).

That said, cooperative multithreading isn’t the same as actual multithreading. So its still single-threaded. And no, Axolot Games cannot implement multithreading in Lua, it’s literally impossible.

So the only solution is just implementing coroutines from the ground up with heavy modifications to the LuaVM while being slower. (This is in our ideas list)
